---
name: Checks
on:
  push:
    branches:
      - main  # Remplace avec ta branche si nécessaire

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKEHUB_USE }}
          password: ${{ secrets.DOCKEHUB_TOKEN }}

      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v2

      # Run tests
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      # Run linting
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
      
      # Example of setting a state or environment variable (to replace save-state command)
      - name: Set environment variable
        run: echo "MY_STATE=my_value" >> $GITHUB_ENV
